name: simple_link_preview
description: Returns a simple metadata to build web link preview.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  universal_html: ^2.0.8
  metadata_fetch: ^0.4.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
