name: simple_link_preview
description: Returns a simple metadata for generating a weblink preview by examining the html <meta> tags.
version: 1.0.1
repository: https://github.com/sonnts996/simple_link_preview

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  universal_html: ^2.0.8
  metadata_fetch: ^0.4.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
