name: simple_link_preview
description: Returns a simple metadata for generating a weblink preview by examining the html <meta> tags.
version: 2.0.0
repository: https://github.com/sonnts996/simple_link_preview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  universal_html: ^2.2.4
  metadata_fetch_plus: ^1.0.0

dev_dependencies:
  owlet_lints: ^3.0.0
  test: ^1.16.0
